// countries.js
// Banco de dados com todos os países, seus códigos, continentes, capitais e níveis de dificuldade.
const countries = [
    // Nível 1 (Muito Fácil)
    { nome: 'Alemanha', codigo: 'de', artigo: 'da', continente: 'Europa', capital: 'Berlim', nivel: 1 },
    { nome: 'Argentina', codigo: 'ar', artigo: 'da', continente: 'América do Sul', capital: 'Buenos Aires', nivel: 1 },
    { nome: 'Austrália', codigo: 'au', artigo: 'da', continente: 'Oceania', capital: 'Camberra', nivel: 1 },
    { nome: 'Brasil', codigo: 'br', artigo: 'do', continente: 'América do Sul', capital: 'Brasília', nivel: 1 },
    { nome: 'Canadá', codigo: 'ca', artigo: 'do', continente: 'América do Norte', capital: 'Otava', nivel: 1 },
    { nome: 'China', codigo: 'cn', artigo: 'da', continente: 'Ásia', capital: 'Pequim', nivel: 1 },
    { nome: 'Egito', codigo: 'eg', artigo: 'do', continente: 'África', capital: 'Cairo', nivel: 1 },
    { nome: 'Espanha', codigo: 'es', artigo: 'da', continente: 'Europa', capital: 'Madri', nivel: 1 },
    { nome: 'Estados Unidos', codigo: 'us', artigo: 'dos', continente: 'América do Norte', capital: 'Washington, D.C.', nivel: 1 },
    { nome: 'França', codigo: 'fr', artigo: 'da', continente: 'Europa', capital: 'Paris', nivel: 1 },
    { nome: 'Índia', codigo: 'in', artigo: 'da', continente: 'Ásia', capital: 'Nova Déli', nivel: 1 },
    { nome: 'Itália', codigo: 'it', artigo: 'da', continente: 'Europa', capital: 'Roma', nivel: 1 },
    { nome: 'Japão', codigo: 'jp', artigo: 'do', continente: 'Ásia', capital: 'Tóquio', nivel: 1 },
    { nome: 'México', codigo: 'mx', artigo: 'do', continente: 'América do Norte', capital: 'Cidade do México', nivel: 1 },
    { nome: 'Portugal', codigo: 'pt', artigo: 'de', continente: 'Europa', capital: 'Lisboa', nivel: 1 },
    { nome: 'Reino Unido', codigo: 'gb', artigo: 'do', continente: 'Europa', capital: 'Londres', nivel: 1 },
    { nome: 'Rússia', codigo: 'ru', artigo: 'da', continente: 'Europa', capital: 'Moscou', nivel: 1 },
    { nome: 'África do Sul', codigo: 'za', artigo: 'da', continente: 'África', capital: 'Pretória', nivel: 1 },

    // Nível 2 (Fácil)
    { nome: 'Arábia Saudita', codigo: 'sa', artigo: 'da', continente: 'Ásia', capital: 'Riade', nivel: 2 },
    { nome: 'Áustria', codigo: 'at', artigo: 'da', continente: 'Europa', capital: 'Viena', nivel: 2 },
    { nome: 'Bélgica', codigo: 'be', artigo: 'da', continente: 'Europa', capital: 'Bruxelas', nivel: 2 },
    { nome: 'Chile', codigo: 'cl', artigo: 'do', continente: 'América do Sul', capital: 'Santiago', nivel: 2 },
    { nome: 'Colômbia', codigo: 'co', artigo: 'da', continente: 'América do Sul', capital: 'Bogotá', nivel: 2 },
    { nome: 'Coreia do Sul', codigo: 'kr', artigo: 'da', continente: 'Ásia', capital: 'Seul', nivel: 2 },
    { nome: 'Cuba', codigo: 'cu', artigo: 'de', continente: 'América Central', capital: 'Havana', nivel: 2 },
    { nome: 'Dinamarca', codigo: 'dk', artigo: 'da', continente: 'Europa', capital: 'Copenhaga', nivel: 2 },
    { nome: 'Emirados Árabes Unidos', codigo: 'ae', artigo: 'dos', continente: 'Ásia', capital: 'Abu Dabi', nivel: 2 },
    { nome: 'Finlândia', codigo: 'fi', artigo: 'da', continente: 'Europa', capital: 'Helsinque', nivel: 2 },
    { nome: 'Grécia', codigo: 'gr', artigo: 'da', continente: 'Europa', capital: 'Atenas', nivel: 2 },
    { nome: 'Holanda', codigo: 'nl', artigo: 'da', continente: 'Europa', capital: 'Amesterdão', nivel: 2 },
    { nome: 'Indonésia', codigo: 'id', artigo: 'da', continente: 'Ásia', capital: 'Jacarta', nivel: 2 },
    { nome: 'Irã', codigo: 'ir', artigo: 'do', continente: 'Ásia', capital: 'Teerã', nivel: 2 },
    { nome: 'Irlanda', codigo: 'ie', artigo: 'da', continente: 'Europa', capital: 'Dublim', nivel: 2 },
    { nome: 'Israel', codigo: 'il', artigo: 'de', continente: 'Ásia', capital: 'Jerusalém', nivel: 2 },
    { nome: 'Jamaica', codigo: 'jm', artigo: 'da', continente: 'América Central', capital: 'Kingston', nivel: 2 },
    { nome: 'Marrocos', codigo: 'ma', artigo: 'do', continente: 'África', capital: 'Rabate', nivel: 2 },
    { nome: 'Nigéria', codigo: 'ng', artigo: 'da', continente: 'África', capital: 'Abuja', nivel: 2 },
    { nome: 'Noruega', codigo: 'no', artigo: 'da', continente: 'Europa', capital: 'Oslo', nivel: 2 },
    { nome: 'Nova Zelândia', codigo: 'nz', artigo: 'da', continente: 'Oceania', capital: 'Wellington', nivel: 2 },
    { nome: 'Paquistão', codigo: 'pk', artigo: 'do', continente: 'Ásia', capital: 'Islamabade', nivel: 2 },
    { nome: 'Peru', codigo: 'pe', artigo: 'do', continente: 'América do Sul', capital: 'Lima', nivel: 2 },
    { nome: 'Polônia', codigo: 'pl', artigo: 'da', continente: 'Europa', capital: 'Varsóvia', nivel: 2 },
    { nome: 'Suécia', codigo: 'se', artigo: 'da', continente: 'Europa', capital: 'Estocolmo', nivel: 2 },
    { nome: 'Suíça', codigo: 'ch', artigo: 'da', continente: 'Europa', capital: 'Berna', nivel: 2 },
    { nome: 'Tailândia', codigo: 'th', artigo: 'da', continente: 'Ásia', capital: 'Banguecoque', nivel: 2 },
    { nome: 'Turquia', codigo: 'tr', artigo: 'da', continente: 'Ásia', capital: 'Ancara', nivel: 2 },
    { nome: 'Ucrânia', codigo: 'ua', artigo: 'da', continente: 'Europa', capital: 'Quieve', nivel: 2 },
    { nome: 'Venezuela', codigo: 've', artigo: 'da', continente: 'América do Sul', capital: 'Caracas', nivel: 2 },
    { nome: 'Vietnã', codigo: 'vn', artigo: 'do', continente: 'Ásia', capital: 'Hanói', nivel: 2 },

    // Nível 3 (Médio)
    { nome: 'Angola', codigo: 'ao', artigo: 'de', continente: 'África', capital: 'Luanda', nivel: 3 },
    { nome: 'Bolívia', codigo: 'bo', artigo: 'da', continente: 'América do Sul', capital: 'Sucre', nivel: 3 },
    { nome: 'Bulgária', codigo: 'bg', artigo: 'da', continente: 'Europa', capital: 'Sófia', nivel: 3 },
    { nome: 'Camarões', codigo: 'cm', artigo: 'dos', continente: 'África', capital: 'Iaundé', nivel: 3 },
    { nome: 'Catar', codigo: 'qa', artigo: 'do', continente: 'Ásia', capital: 'Doa', nivel: 3 },
    { nome: 'Cazaquistão', codigo: 'kz', artigo: 'do', continente: 'Ásia', capital: 'Astana', nivel: 3 },
    { nome: 'Costa Rica', codigo: 'cr', artigo: 'da', continente: 'América Central', capital: 'São José', nivel: 3 },
    { nome: 'Croácia', codigo: 'hr', artigo: 'da', continente: 'Europa', capital: 'Zagrebe', nivel: 3 },
    { nome: 'Equador', codigo: 'ec', artigo: 'do', continente: 'América do Sul', capital: 'Quito', nivel: 3 },
    { nome: 'Eslováquia', codigo: 'sk', artigo: 'da', continente: 'Europa', capital: 'Bratislava', nivel: 3 },
    { nome: 'Etiópia', codigo: 'et', artigo: 'da', continente: 'África', capital: 'Adis Abeba', nivel: 3 },
    { nome: 'Filipinas', codigo: 'ph', artigo: 'das', continente: 'Ásia', capital: 'Manila', nivel: 3 },
    { nome: 'Gana', codigo: 'gh', artigo: 'de', continente: 'África', capital: 'Acra', nivel: 3 },
    { nome: 'Hungria', codigo: 'hu', artigo: 'da', continente: 'Europa', capital: 'Budapeste', nivel: 3 },
    { nome: 'Iraque', codigo: 'iq', artigo: 'do', continente: 'Ásia', capital: 'Bagdá', nivel: 3 },
    { nome: 'Islândia', codigo: 'is', artigo: 'da', continente: 'Europa', capital: 'Reiquiavique', nivel: 3 },
    { nome: 'Líbano', codigo: 'lb', artigo: 'do', continente: 'Ásia', capital: 'Beirute', nivel: 3 },
    { nome: 'Lituânia', codigo: 'lt', artigo: 'da', continente: 'Europa', capital: 'Vílnius', nivel: 3 },
    { nome: 'Malásia', codigo: 'my', artigo: 'da', continente: 'Ásia', capital: 'Cuala Lumpur', nivel: 3 },
    { nome: 'Moçambique', codigo: 'mz', artigo: 'de', continente: 'África', capital: 'Maputo', nivel: 3 },
    { nome: 'Panamá', codigo: 'pa', artigo: 'do', continente: 'América Central', capital: 'Cidade do Panamá', nivel: 3 },
    { nome: 'Paraguai', codigo: 'py', artigo: 'do', continente: 'América do Sul', capital: 'Assunção', nivel: 3 },
    { nome: 'Quênia', codigo: 'ke', artigo: 'do', continente: 'África', capital: 'Nairóbi', nivel: 3 },
    { nome: 'República Dominicana', codigo: 'do', artigo: 'da', continente: 'América Central', capital: 'São Domingos', nivel: 3 },
    { nome: 'República Tcheca', codigo: 'cz', artigo: 'da', continente: 'Europa', capital: 'Praga', nivel: 3 },
    { nome: 'Romênia', codigo: 'ro', artigo: 'da', continente: 'Europa', capital: 'Bucareste', nivel: 3 },
    { nome: 'Senegal', codigo: 'sn', artigo: 'do', continente: 'África', capital: 'Dacar', nivel: 3 },
    { nome: 'Sérvia', codigo: 'rs', artigo: 'da', continente: 'Europa', capital: 'Belgrado', nivel: 3 },
    { nome: 'Singapura', codigo: 'sg', artigo: 'de', continente: 'Ásia', capital: 'Singapura', nivel: 3 },
    { nome: 'Síria', codigo: 'sy', artigo: 'da', continente: 'Ásia', capital: 'Damasco', nivel: 3 },
    { nome: 'Tanzânia', codigo: 'tz', artigo: 'da', continente: 'África', capital: 'Dodoma', nivel: 3 },
    { nome: 'Tunísia', codigo: 'tn', artigo: 'da', continente: 'África', capital: 'Tunes', nivel: 3 },
    { nome: 'Uruguai', codigo: 'uy', artigo: 'do', continente: 'América do Sul', capital: 'Montevidéu', nivel: 3 },
    { nome: 'Uzbequistão', codigo: 'uz', artigo: 'do', continente: 'Ásia', capital: 'Tasquente', nivel: 3 },

    // Nível 4 (Difícil)
    { nome: 'Afeganistão', codigo: 'af', artigo: 'do', continente: 'Ásia', capital: 'Cabul', nivel: 4 },
    { nome: 'Albânia', codigo: 'al', artigo: 'da', continente: 'Europa', capital: 'Tirana', nivel: 4 },
    { nome: 'Argélia', codigo: 'dz', artigo: 'da', continente: 'África', capital: 'Argel', nivel: 4 },
    { nome: 'Azerbaijão', codigo: 'az', artigo: 'do', continente: 'Ásia', capital: 'Bacu', nivel: 4 },
    { nome: 'Bangladesh', codigo: 'bd', artigo: 'de', continente: 'Ásia', capital: 'Daca', nivel: 4 },
    { nome: 'Bielorrússia', codigo: 'by', artigo: 'da', continente: 'Europa', capital: 'Minsque', nivel: 4 },
    { nome: 'Bósnia e Herzegovina', codigo: 'ba', artigo: 'da', continente: 'Europa', capital: 'Saraievo', nivel: 4 },
    { nome: 'Butão', codigo: 'bt', artigo: 'do', continente: 'Ásia', capital: 'Timbu', nivel: 4 },
    { nome: 'Camboja', codigo: 'kh', artigo: 'do', continente: 'Ásia', capital: 'Pnom Pene', nivel: 4 },
    { nome: 'Coreia do Norte', codigo: 'kp', artigo: 'da', continente: 'Ásia', capital: 'Piongueangue', nivel: 4 },
    { nome: 'Costa do Marfim', codigo: 'ci', artigo: 'da', continente: 'África', capital: 'Iamussucro', nivel: 4 },
    { nome: 'El Salvador', codigo: 'sv', artigo: 'de', continente: 'América Central', capital: 'São Salvador', nivel: 4 },
    { nome: 'Eslovênia', codigo: 'si', artigo: 'da', continente: 'Europa', capital: 'Liubliana', nivel: 4 },
    { nome: 'Estônia', codigo: 'ee', artigo: 'da', continente: 'Europa', capital: 'Talim', nivel: 4 },
    { nome: 'Geórgia', codigo: 'ge', artigo: 'da', continente: 'Ásia', capital: 'Tebilíssi', nivel: 4 },
    { nome: 'Guatemala', codigo: 'gt', artigo: 'da', continente: 'América Central', capital: 'Cidade da Guatemala', nivel: 4 },
    { nome: 'Honduras', codigo: 'hn', artigo: 'de', continente: 'América Central', capital: 'Tegucigalpa', nivel: 4 },
    { nome: 'Jordânia', codigo: 'jo', artigo: 'da', continente: 'Ásia', capital: 'Amã', nivel: 4 },
    { nome: 'Kuwait', codigo: 'kw', artigo: 'do', continente: 'Ásia', capital: 'Cidade do Kuwait', nivel: 4 },
    { nome: 'Laos', codigo: 'la', artigo: 'do', continente: 'Ásia', capital: 'Vienciana', nivel: 4 },
    { nome: 'Letônia', codigo: 'lv', artigo: 'da', continente: 'Europa', capital: 'Riga', nivel: 4 },
    { nome: 'Líbia', codigo: 'ly', artigo: 'da', continente: 'África', capital: 'Trípoli', nivel: 4 },
    { nome: 'Macedônia do Norte', codigo: 'mk', artigo: 'da', continente: 'Europa', capital: 'Escópia', nivel: 4 },
    { nome: 'Madagáscar', codigo: 'mg', artigo: 'de', continente: 'África', capital: 'Antananarivo', nivel: 4 },
    { nome: 'Moldávia', codigo: 'md', artigo: 'da', continente: 'Europa', capital: 'Quixinau', nivel: 4 },
    { nome: 'Mongólia', codigo: 'mn', artigo: 'da', continente: 'Ásia', capital: 'Ulã Bator', nivel: 4 },
    { nome: 'Myanmar', codigo: 'mm', artigo: 'de', continente: 'Ásia', capital: 'Nepiedó', nivel: 4 },
    { nome: 'Namíbia', codigo: 'na', artigo: 'da', continente: 'África', capital: 'Vinduque', nivel: 4 },
    { nome: 'Nepal', codigo: 'np', artigo: 'do', continente: 'Ásia', capital: 'Catmandu', nivel: 4 },
    { nome: 'Nicarágua', codigo: 'ni', artigo: 'da', continente: 'América Central', capital: 'Manágua', nivel: 4 },
    { nome: 'Quirguistão', codigo: 'kg', artigo: 'do', continente: 'Ásia', capital: 'Bisqueque', nivel: 4 },
    { nome: 'Somália', codigo: 'so', artigo: 'da', continente: 'África', capital: 'Mogadíscio', nivel: 4 },
    { nome: 'Sudão', codigo: 'sd', artigo: 'do', continente: 'África', capital: 'Cartum', nivel: 4 },
    { nome: 'Tajiquistão', codigo: 'tj', artigo: 'do', continente: 'Ásia', capital: 'Duchambé', nivel: 4 },
    { nome: 'Turcomenistão', codigo: 'tm', artigo: 'do', continente: 'Ásia', capital: 'Asgabate', nivel: 4 },
    { nome: 'Zâmbia', codigo: 'zm', artigo: 'da', continente: 'África', capital: 'Lusaca', nivel: 4 },
    { nome: 'Zimbábue', codigo: 'zw', artigo: 'do', continente: 'África', capital: 'Harare', nivel: 4 },

    // Nível 5 (Expert)
    { nome: 'Andorra', codigo: 'ad', artigo: 'de', continente: 'Europa', capital: 'Andorra-a-Velha', nivel: 5 },
    { nome: 'Antígua e Barbuda', codigo: 'ag', artigo: 'de', continente: 'América Central', capital: 'São João', nivel: 5 },
    { nome: 'Bahamas', codigo: 'bs', artigo: 'das', continente: 'América Central', capital: 'Nassau', nivel: 5 },
    { nome: 'Barbados', codigo: 'bb', artigo: 'de', continente: 'América Central', capital: 'Bridgetown', nivel: 5 },
    { nome: 'Barein', codigo: 'bh', artigo: 'do', continente: 'Ásia', capital: 'Manama', nivel: 5 },
    { nome: 'Belize', codigo: 'bz', artigo: 'de', continente: 'América Central', capital: 'Belmopã', nivel: 5 },
    { nome: 'Benin', codigo: 'bj', artigo: 'do', continente: 'África', capital: 'Porto Novo', nivel: 5 },
    { nome: 'Botsuana', codigo: 'bw', artigo: 'de', continente: 'África', capital: 'Gaborone', nivel: 5 },
    { nome: 'Brunei', codigo: 'bn', artigo: 'de', continente: 'Ásia', capital: 'Bandar Seri Begauã', nivel: 5 },
    { nome: 'Burquina Faso', codigo: 'bf', artigo: 'de', continente: 'África', capital: 'Uagadugu', nivel: 5 },
    { nome: 'Burundi', codigo: 'bi', artigo: 'do', continente: 'África', capital: 'Gitega', nivel: 5 },
    { nome: 'Cabo Verde', codigo: 'cv', artigo: 'de', continente: 'África', capital: 'Praia', nivel: 5 },
    { nome: 'Chade', codigo: 'td', artigo: 'do', continente: 'África', capital: 'Jamena', nivel: 5 },
    { nome: 'Comores', codigo: 'km', artigo: 'de', continente: 'África', capital: 'Moroni', nivel: 5 },
    { nome: 'Djibuti', codigo: 'dj', artigo: 'do', continente: 'África', capital: 'Djibuti', nivel: 5 },
    { nome: 'Dominica', codigo: 'dm', artigo: 'da', continente: 'América Central', capital: 'Roseau', nivel: 5 },
    { nome: 'Eritreia', codigo: 'er', artigo: 'da', continente: 'África', capital: 'Asmara', nivel: 5 },
    { nome: 'Fiji', codigo: 'fj', artigo: 'de', continente: 'Oceania', capital: 'Suva', nivel: 5 },
    { nome: 'Gabão', codigo: 'ga', artigo: 'do', continente: 'África', capital: 'Librevile', nivel: 5 },
    { nome: 'Gâmbia', codigo: 'gm', artigo: 'da', continente: 'África', capital: 'Banjul', nivel: 5 },
    { nome: 'Granada', codigo: 'gd', artigo: 'de', continente: 'América Central', capital: 'São Jorge', nivel: 5 },
    { nome: 'Guiné', codigo: 'gn', artigo: 'da', continente: 'África', capital: 'Conacri', nivel: 5 },
    { nome: 'Guiné Equatorial', codigo: 'gq', artigo: 'da', continente: 'África', capital: 'Malabo', nivel: 5 },
    { nome: 'Guiné-Bissau', codigo: 'gw', artigo: 'da', continente: 'África', capital: 'Bissau', nivel: 5 },
    { nome: 'Guiana', codigo: 'gy', artigo: 'da', continente: 'América do Sul', capital: 'Georgetown', nivel: 5 },
    { nome: 'Haiti', codigo: 'ht', artigo: 'do', continente: 'América Central', capital: 'Porto Príncipe', nivel: 5 },
    { nome: 'Ilhas Marshall', codigo: 'mh', artigo: 'das', continente: 'Oceania', capital: 'Majuro', nivel: 5 },
    { nome: 'Ilhas Salomão', codigo: 'sb', artigo: 'das', continente: 'Oceania', capital: 'Honiara', nivel: 5 },
    { nome: 'Kiribati', codigo: 'ki', artigo: 'do', continente: 'Oceania', capital: 'Taraua do Sul', nivel: 5 },
    { nome: 'Lesoto', codigo: 'ls', artigo: 'do', continente: 'África', capital: 'Maseru', nivel: 5 },
    { nome: 'Libéria', codigo: 'lr', artigo: 'da', continente: 'África', capital: 'Monróvia', nivel: 5 },
    { nome: 'Liechtenstein', codigo: 'li', artigo: 'de', continente: 'Europa', capital: 'Vaduz', nivel: 5 },
    { nome: 'Luxemburgo', codigo: 'lu', artigo: 'de', continente: 'Europa', capital: 'Luxemburgo', nivel: 5 },
    { nome: 'Malaui', codigo: 'mw', artigo: 'do', continente: 'África', capital: 'Lilongué', nivel: 5 },
    { nome: 'Maldivas', codigo: 'mv', artigo: 'das', continente: 'Ásia', capital: 'Malé', nivel: 5 },
    { nome: 'Mali', codigo: 'ml', artigo: 'do', continente: 'África', capital: 'Bamaco', nivel: 5 },
    { nome: 'Malta', codigo: 'mt', artigo: 'de', continente: 'Europa', capital: 'Valeta', nivel: 5 },
    { nome: 'Maurício', codigo: 'mu', artigo: 'de', continente: 'África', capital: 'Porto Luís', nivel: 5 },
    { nome: 'Mauritânia', codigo: 'mr', artigo: 'da', continente: 'África', capital: 'Nuaquechote', nivel: 5 },
    { nome: 'Micronésia', codigo: 'fm', artigo: 'da', continente: 'Oceania', capital: 'Paliquir', nivel: 5 },
    { nome: 'Mônaco', codigo: 'mc', artigo: 'de', continente: 'Europa', capital: 'Mônaco', nivel: 5 },
    { nome: 'Montenegro', codigo: 'me', artigo: 'de', continente: 'Europa', capital: 'Podgoritsa', nivel: 5 },
    { nome: 'Nauru', codigo: 'nr', artigo: 'de', continente: 'Oceania', capital: 'Iarém', nivel: 5 },
    { nome: 'Níger', codigo: 'ne', artigo: 'do', continente: 'África', capital: 'Niamei', nivel: 5 },
    { nome: 'Omã', codigo: 'om', artigo: 'de', continente: 'Ásia', capital: 'Mascate', nivel: 5 },
    { nome: 'Palau', codigo: 'pw', artigo: 'de', continente: 'Oceania', capital: 'Ngerulmud', nivel: 5 },
    { nome: 'Papua-Nova Guiné', codigo: 'pg', artigo: 'da', continente: 'Oceania', capital: 'Porto Moresby', nivel: 5 },
    { nome: 'República Centro-Africana', codigo: 'cf', artigo: 'da', continente: 'África', capital: 'Bangui', nivel: 5 },
    { nome: 'República Democrática do Congo', codigo: 'cd', artigo: 'da', continente: 'África', capital: 'Quinxassa', nivel: 5 },
    { nome: 'Ruanda', codigo: 'rw', artigo: 'de', continente: 'África', capital: 'Quigali', nivel: 5 },
    { nome: 'Samoa', codigo: 'ws', artigo: 'de', continente: 'Oceania', capital: 'Apia', nivel: 5 },
    { nome: 'San Marino', codigo: 'sm', artigo: 'de', continente: 'Europa', capital: 'São Marinho', nivel: 5 },
    { nome: 'Santa Lúcia', codigo: 'lc', artigo: 'de', continente: 'América Central', capital: 'Castries', nivel: 5 },
    { nome: 'São Cristóvão e Névis', codigo: 'kn', artigo: 'de', continente: 'América Central', capital: 'Basseterre', nivel: 5 },
    { nome: 'São Tomé e Príncipe', codigo: 'st', artigo: 'de', continente: 'África', capital: 'São Tomé', nivel: 5 },
    { nome: 'São Vicente e Granadinas', codigo: 'vc', artigo: 'de', continente: 'América Central', capital: 'Kingstown', nivel: 5 },
    { nome: 'Serra Leoa', codigo: 'sl', artigo: 'da', continente: 'África', capital: 'Freetown', nivel: 5 },
    { nome: 'Seicheles', codigo: 'sc', artigo: 'de', continente: 'África', capital: 'Victória', nivel: 5 },
    { nome: 'Sri Lanka', codigo: 'lk', artigo: 'do', continente: 'Ásia', capital: 'Sri Jaiavardenapura-Cota', nivel: 5 },
    { nome: 'Suazilândia', codigo: 'sz', artigo: 'da', continente: 'África', capital: 'Lobamba', nivel: 5 },
    { nome: 'Sudão do Sul', codigo: 'ss', artigo: 'do', continente: 'África', capital: 'Juba', nivel: 5 },
    { nome: 'Suriname', codigo: 'sr', artigo: 'da', continente: 'América do Sul', capital: 'Paramaribo', nivel: 5 },
    { nome: 'Timor-Leste', codigo: 'tl', artigo: 'do', continente: 'Ásia', capital: 'Díli', nivel: 5 },
    { nome: 'Togo', codigo: 'tg', artigo: 'do', continente: 'África', capital: 'Lomé', nivel: 5 },
    { nome: 'Tonga', codigo: 'to', artigo: 'de', continente: 'Oceania', capital: 'Nucualofa', nivel: 5 },
    { nome: 'Trindade e Tobago', codigo: 'tt', artigo: 'de', continente: 'América Central', capital: 'Porto de Espanha', nivel: 5 },
    { nome: 'Tuvalu', codigo: 'tv', artigo: 'de', continente: 'Oceania', capital: 'Funafuti', nivel: 5 },
    { nome: 'Uganda', 'codigo': 'ug', artigo: 'de', continente: 'África', capital: 'Campala', nivel: 5 },
    { nome: 'Vanuatu', codigo: 'vu', artigo: 'de', continente: 'Oceania', capital: 'Porto Vila', nivel: 5 },
    { nome: 'Iêmen', codigo: 'ye', artigo: 'do', continente: 'Ásia', capital: 'Saná', nivel: 5 }
];
