// curiosities_br.js
// "Saiba mais" das seções brasileiras: história de cada bandeira de estado
// e uma explicação de cada paisagem/ponto turístico das capitais.
// Textos usados no álbum e para gerar áudio (voz de assets/audio/bandeiras/brasil.mp3).

const CURIOSITIES_BR = {
  // ---- HISTÓRIA DAS BANDEIRAS DOS ESTADOS ----
  bandeiras: {
    AC: "A bandeira do Acre nasceu na Revolução Acreana, movimento que separou a região da Bolívia entre 1899 e 1903. A faixa diagonal verde sobre o campo amarelo representa o caminho para o progresso, e a estrela vermelha lembra o sangue derramado pelos seringueiros que lutaram pela anexação ao Brasil.",
    AL: "A bandeira de Alagoas foi adotada em 1963. As faixas vermelha, branca e azul remetem às cores usadas nas revoltas do século XIX, e o brasão central traz um ramo de algodão, um de cana-de-açúcar e um coqueiro — as riquezas agrícolas que marcaram a economia do estado.",
    AP: "A bandeira do Amapá é de 1984, ano em que o território virou estado. O verde simboliza as florestas, o azul o céu e as águas, o branco a paz e o amarelo as riquezas minerais. A faixa preta é uma homenagem aos que morreram defendendo o território, e a Fortaleza de São José aparece estilizada à esquerda.",
    AM: "A bandeira do Amazonas é de 1897. As 25 estrelas pequenas representavam os municípios da época e a estrela maior, o próprio Amazonas. A faixa branca no alto com listras vermelhas nas pontas guarda semelhança com bandeiras de inspiração norte-americana, comuns no início da República.",
    BA: "A bandeira da Bahia lembra a Conjuração Baiana de 1798, também chamada Revolta dos Alfaiates. O triângulo vermelho com fundo branco e a faixa azul foram inspirados na bandeira usada pelos revoltosos, que sonhavam com uma república baiana independente.",
    CE: "A bandeira do Ceará segue o modelo da bandeira nacional, com losango e círculo, mas com o brasão do estado no centro. Foi adotada em 1922 e substituiu versões anteriores ligadas ao movimento republicano local.",
    DF: "A bandeira do Distrito Federal foi criada pelo poeta Guilherme de Almeida em 1969. O retângulo verde dividido por faixas brancas em ângulo reto representa as vias e o traçado planejado de Brasília, e as quatro setas apontam para a capital como ponto de convergência do país.",
    ES: "A bandeira do Espírito Santo é de 1908. As faixas azul, branca e rosa vêm das cores da Casa de Habsburgo-Lorena, ligada a Dom Pedro II. O lema 'Trabalha e Confia', em português, resume o espírito do estado.",
    GO: "A bandeira de Goiás é de 1919 e mistura o modelo dos Estados Unidos — faixas horizontais e um retângulo azul com estrelas — com o Cruzeiro do Sul. As cinco estrelas representam a constelação vista no céu goiano.",
    MA: "A bandeira do Maranhão foi desenhada por Joaquim Sousândrade em 1889. As faixas brancas, pretas e vermelhas representam as três etnias que formaram o povo maranhense, e a estrela branca no retângulo azul é Beta Escorpião, associada ao estado no céu.",
    MT: "A bandeira de Mato Grosso é de 1890. O losango branco sobre fundo azul e verde traz uma estrela dourada de cinco pontas ligada ao ramo republicano. As cores remetem ao céu e às matas do estado.",
    MS: "Mato Grosso do Sul foi criado em 1977, e sua bandeira é do ano seguinte. A faixa branca em diagonal separa o azul do céu do verde da terra, e a estrela amarela representa o novo estado surgindo no mapa do Brasil.",
    MG: "A bandeira de Minas Gerais é o estandarte da Inconfidência Mineira de 1789. O triângulo vermelho sobre fundo branco e a frase latina 'Libertas Quae Sera Tamen' — 'Liberdade ainda que tardia' — eram o símbolo escolhido pelos inconfidentes para a república que não chegou a existir.",
    PA: "A bandeira do Pará é de 1889. A faixa vermelha em diagonal com uma estrela branca — a estrela Spica, da constelação de Virgem — corta o fundo branco. É uma das bandeiras estaduais mais antigas ainda em uso.",
    PB: "A bandeira da Paraíba tem a palavra 'NEGO' em letras garrafais sobre o vermelho, e a data 26 de julho de 1930. Ela marca a recusa do presidente paraibano João Pessoa em apoiar o candidato do governo federal — episódio que ajudou a desencadear a Revolução de 1930. O preto é o luto por seu assassinato.",
    PR: "A bandeira do Paraná é de 1947 e traz a esfera armilar azul com o Cruzeiro do Sul, cercada por um ramo de pinheiro e um de erva-mate, as duas plantas símbolo do estado. A faixa branca em diagonal atravessa o fundo verde.",
    PE: "A bandeira de Pernambuco vem da Revolução Pernambucana de 1817, movimento republicano contra a Coroa portuguesa. O arco-íris, o sol e a estrela sobre a faixa azul representam a paz, a luz e a união do povo; a cruz branca no campo vermelho completa o desenho.",
    PI: "A bandeira do Piauí é de 1922. O retângulo azul no canto com uma estrela branca lembra a bandeira nacional, e as faixas verdes e amarelas representam a esperança e as riquezas do estado. A estrela homenageia a Batalha do Jenipapo, travada em solo piauiense pela Independência.",
    RJ: "A bandeira do Rio de Janeiro é de 1965, quando estado da Guanabara e antigo estado do Rio ainda eram separados; a versão atual é de 1975. Traz o brasão com a águia imperial e o Pão de Açúcar, sobre fundo branco e azul.",
    RN: "A bandeira do Rio Grande do Norte é de 1957. As cores branca e vermelha e o brasão com a Fortaleza dos Reis Magos, o coqueiro e a data de fundação de Natal — 25 de dezembro de 1599 — resumem a história do estado.",
    RS: "A bandeira do Rio Grande do Sul nasceu na Revolução Farroupilha (1835–1845), a mais longa guerra civil do Brasil. As faixas verde, vermelha e amarela e o brasão com o lema 'Liberdade, Igualdade, Humanidade' eram o símbolo da República Rio-Grandense proclamada pelos farrapos.",
    RO: "Rondônia virou estado em 1981, e sua bandeira é do mesmo ano. A faixa branca em diagonal com uma estrela amarela separa o verde das florestas do azul do céu — desenho parecido com o de outros estados criados na mesma época.",
    RR: "A bandeira de Roraima é de 1996. As faixas verde, amarela e azul representam a floresta, as savanas e os rios; a faixa vermelha com uma estrela branca simboliza a linha do Equador cruzando o estado e a força do povo roraimense.",
    SC: "A bandeira de Santa Catarina é de 1953. O losango vermelho sobre fundo branco e verde traz o brasão do estado, com uma chave — referência à posição estratégica do porto — e a data de 17 de novembro de 1889, quando o estado aderiu à República.",
    SP: "A bandeira de São Paulo foi desenhada por Júlio Ribeiro em 1888, ainda no Império, como símbolo abolicionista e republicano. As 13 faixas pretas e brancas representam os dias e as noites de luta, o retângulo azul traz a Cruz do Sul e a silhueta do mapa do Brasil no centro.",
    SE: "A bandeira de Sergipe é de 1920. As faixas verdes e amarelas e as cinco estrelas brancas no retângulo azul representam os cinco então maiores municípios do estado; o verde e o amarelo remetem às cores nacionais.",
    TO: "Tocantins foi separado de Goiás em 1988, e sua bandeira, criada pelo artista Aldo Marostica, é de 1989. As faixas amarela, branca e azul representam o sol, a paz e as águas; é a bandeira estadual mais recente do Brasil.",
  },

  // ---- PAISAGENS DAS CAPITAIS (ponto turístico) ----
  paisagens: {
    AC: "O Palácio Rio Branco, em Rio Branco, foi por muitas décadas a sede do governo do Acre. O prédio atual, em estilo neoclássico, é de 1930 e hoje funciona como museu, contando a história da Revolução Acreana e da economia da borracha que levou a região a ser incorporada ao Brasil.",
    AL: "A Praia de Pajuçara, em Maceió, é conhecida pelas piscinas naturais que se formam na maré baixa a cerca de dois quilômetros da costa, onde os visitantes chegam de jangada. As jangadas coloridas com vela triangular são o símbolo do litoral alagoano.",
    AP: "A Fortaleza de São José de Macapá é a maior fortificação colonial portuguesa do Brasil. Construída entre 1764 e 1782 com pedra, óleo de baleia e mão de obra indígena e escravizada, servia para proteger a foz do rio Amazonas de invasores.",
    AM: "O Teatro Amazonas, em Manaus, foi inaugurado em 1896 no auge do ciclo da borracha, quando a cidade era uma das mais ricas do mundo. Sua cúpula é coberta por 36 mil peças de cerâmica nas cores da bandeira do Brasil, e boa parte do material — mármore, ferro, lustres — veio da Europa.",
    BA: "O Elevador Lacerda liga a Cidade Baixa à Cidade Alta de Salvador, vencendo cerca de 72 metros de desnível. Inaugurado em 1873 e movido a vapor, foi o primeiro elevador urbano do Brasil; hoje transporta milhares de pessoas por dia em poucos segundos.",
    CE: "A Ponte dos Ingleses, ou Ponte Metálica, em Fortaleza, foi construída no início do século XX por engenheiros britânicos para ser um porto — projeto que não deu certo por causa do assoreamento. Virou cartão-postal e ponto famoso para ver o pôr do sol e, às vezes, golfinhos.",
    DF: "O Congresso Nacional, projetado por Oscar Niemeyer, é o coração de Brasília. As duas torres abrigam os gabinetes; a cúpula voltada para cima é o plenário do Senado e a voltada para baixo, o da Câmara dos Deputados. O conjunto foi inaugurado com a cidade, em 1960.",
    ES: "O Convento da Penha, erguido sobre um penhasco de 154 metros em Vila Velha, na Grande Vitória, é um dos santuários mais antigos do Brasil — começou a ser construído em 1558. A vista do alto abrange a baía, a Terceira Ponte e o porto de Vitória.",
    GO: "O Monumento às Três Raças, no Centro de Goiânia, é uma escultura em bronze do artista Neusa Morais que representa o indígena, o negro e o branco erguendo juntos um obelisco. Ficou pronto em 1968 e virou símbolo da capital.",
    MA: "O Palácio dos Leões, em São Luís, é a sede do governo do Maranhão desde o século XVIII e foi construído sobre um antigo forte francês. O nome vem das estátuas de leões na entrada. São Luís tem o maior conjunto de sobrados coloniais portugueses da América Latina, tombado pela Unesco.",
    MT: "A Igreja de Nossa Senhora do Rosário e São Benedito, em Cuiabá, é a mais antiga da cidade. Erguida no século XVIII por uma irmandade de negros escravizados e libertos, sua fachada simples e branca guarda a memória da devoção popular no início da história cuiabana.",
    MS: "A Morada dos Baís, em Campo Grande, é um casarão de 1918 que pertenceu à família Baís, pioneira da cidade. Restaurado, hoje abriga um centro cultural e um café, sendo um dos poucos prédios do começo do século XX preservados na capital.",
    MG: "A Praça da Liberdade, em Belo Horizonte, foi projetada junto com a cidade, em 1897, para ser o centro do poder. Cercada por palácios ecléticos e por filas de palmeiras imperiais, hoje é um circuito cultural com vários museus instalados nos antigos prédios do governo.",
    PA: "O Theatro da Paz, em Belém, foi inaugurado em 1878, também graças à riqueza da borracha. Em estilo neoclássico, com pinturas, mármore de Carrara e lustres de cristal, é um dos teatros mais imponentes do país e continua em plena atividade.",
    PB: "A Estação Cabo Branco, em João Pessoa, foi projetada por Oscar Niemeyer e inaugurada em 2008 como um espaço de ciência, cultura e arte. Fica perto da Ponta do Seixas, o ponto mais oriental das Américas — de onde o sol nasce primeiro no continente.",
    PR: "O Jardim Botânico de Curitiba foi aberto em 1991 e sua estufa de vidro e metal, inspirada nos palácios de cristal do século XIX, virou o cartão-postal da cidade. Os jardins geométricos à francesa na frente da estufa completam a imagem mais fotografada de Curitiba.",
    PE: "O Marco Zero, na Praça Rio Branco, no bairro do Recife Antigo, é o ponto de onde as distâncias da cidade são medidas. Ao redor ficam prédios históricos do porto e, à frente, o Parque das Esculturas de Francisco Brennand, sobre um molhe no mar.",
    PI: "A Ponte Estaiada Mestre João Isidoro França, sobre o rio Poti em Teresina, tem um mirante circular a 75 metros de altura no topo de seu mastro. Inaugurada em 2010, virou símbolo moderno da capital, iluminada à noite.",
    RJ: "O Cristo Redentor, no alto do Morro do Corcovado a 710 metros, foi inaugurado em 1931. A estátua tem 30 metros de altura mais 8 de pedestal, os braços abertos medem 28 metros, e é uma das Sete Maravilhas do Mundo Moderno.",
    RN: "A Fortaleza dos Reis Magos, em Natal, tem formato de estrela de cinco pontas e foi iniciada em 1598, no dia dos Reis Magos — daí o nome. Fica na barra do Rio Potengi e é considerada o marco de fundação da cidade.",
    RS: "A Usina do Gasômetro, em Porto Alegre, era uma termelétrica movida a carvão, inaugurada em 1928. Desativada, foi transformada em centro cultural em 1991. Sua chaminé de 117 metros e o pôr do sol sobre o Lago Guaíba, atrás do prédio, são clássicos da cidade.",
    RO: "A Locomotiva da Estrada de Ferro Madeira-Mamoré, em Porto Velho, lembra a ferrovia construída entre 1907 e 1912 para escoar a borracha da Bolívia. A obra atravessou a floresta e custou milhares de vidas, ficando conhecida como 'a ferrovia do diabo'. Trechos e locomotivas foram preservados como museu.",
    RR: "O Monumento ao Garimpeiro, na orla do Rio Branco em Boa Vista, homenageia os garimpeiros que povoaram a região em busca de ouro e diamante. Boa Vista é a única capital brasileira totalmente ao norte da linha do Equador e tem traçado em leque, com ruas que partem de uma praça central.",
    SC: "A Ponte Hercílio Luz liga a ilha ao continente em Florianópolis. Inaugurada em 1926, é a maior ponte pênsil do Brasil, com 821 metros. Ficou fechada por décadas para reforma e foi reaberta em 2019, voltando a ser o símbolo da cidade.",
    SP: "O MASP, na Avenida Paulista, foi projetado por Lina Bo Bardi e inaugurado em 1968. O prédio se sustenta em quatro pilotis vermelhos, deixando um vão livre de 74 metros embaixo — o maior do mundo na época — que virou praça pública e palco de manifestações.",
    SE: "A Passarela do Caranguejo fica na Orla de Atalaia, em Aracaju, e é marcada por uma grande escultura de caranguejo. A orla, planejada e cheia de bares de frutos do mar, é o principal ponto de encontro e lazer da capital sergipana.",
    TO: "A Praça dos Girassóis, em Palmas, é uma das maiores praças do mundo, com cerca de 570 mil metros quadrados. No centro fica o Palácio Araguaia, sede do governo. Palmas foi construída do zero a partir de 1989 para ser a capital do novo estado do Tocantins.",
  },
};

if (typeof window !== 'undefined') window.CURIOSITIES_BR = CURIOSITIES_BR;
